-   id: svgo
    name: svgo
    description: ''
    entry: svgo
    language: node
    'types': [svg]
    args: []
    require_serial: false
    additional_dependencies: ["svgo@0.5.6"]
    minimum_pre_commit_version: '0'
